---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Include s1_agent_install
      ansible.builtin.include_role:
        name: s1_agent_install
      vars:
        s1_reboot_handler_name: Reboot Node | {{ ansible_os_family }} | Unit Testing

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Show agent version
      ansible.builtin.debug:
        var: s1_agent_version

    - name: Persist facts for verify step
      ansible.builtin.set_fact:
        s1_molecule_installed_src: "{{ s1_agent_src }}"
        # yamllint disable-line rule:line-length
        s1_molecule_installed_version: "{{ s1_agent_version if ansible_os_family != 'Windows' else s1_agent_version | regex_replace('(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)', '\\1.\\2.\\4') }}"
        cacheable: yes

    - name: Show s1_molecule_installed_version
      ansible.builtin.debug:
        var: s1_molecule_installed_version
