---
# verify tasks file for s1_agent_install
- name: Gather package facts | Linux
  ansible.builtin.package_facts:
    manager: auto

- name: Gather service facts | Linux
  ansible.builtin.service_facts:

- name: Assert SentinelOne Agent is upgraded | Linux
  ansible.builtin.assert:
    that:
      - ansible_facts.packages[s1_package_name] is defined
      - ansible_facts.packages[s1_package_name] | map(attribute='version') | list | first == s1_molecule_upgraded_version
      - ansible_facts.packages[s1_package_name] | map(attribute='version') | list | first > s1_molecule_prior_version

- name: Assert SentinelOne service is running | Linux
  ansible.builtin.assert:
    that:
      - ansible_facts.services[s1_service_name] is defined
      - ansible_facts.services[s1_service_name]['state'] == 'running'
      - ansible_facts.services[s1_service_name]['status'] == 'enabled'
