---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Include s1_agent_download
      ansible.builtin.include_role:
        name: s1_agent_download

    - name: Show downloaded agent path
      ansible.builtin.debug:
        var: s1_agent_src

    - name: Persist facts
      ansible.builtin.set_fact:
        s1_molecule_installed_src: "{{ s1_agent_src }}"
        s1_molecule_installed_version: "{{ s1_agent_version }}"
        cacheable: true
