---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Assert that s1_agent_src is defined
      ansible.builtin.assert:
        that:
          - s1_molecule_installed_src is defined
          - s1_molecule_installed_src is not none
          - s1_molecule_installed_src | length > 0

    - name: Get SentinelOne Agent
      ansible.builtin.stat:
        path: "{{ s1_molecule_installed_src }}"
      register: s1_agent_stat
      delegate_to: localhost

    - name: Assert that SentinelOne Agent was downloaded
      ansible.builtin.assert:
        that: s1_agent_stat.stat.exists
