---
- name: Prepare
  hosts: all
  gather_facts: true
  gather_subset:
    - "!all"
    - "!hardware"
    - min
  vars:
    s1_release_n_minus: 1
  tasks:
    - name: Include tasks to clean up package managers | Linux
      ansible.builtin.include_tasks:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/common/templates/tasks/prepare_package_manager.yml"
      when:
        - ansible_system == 'Linux'

    - name: Include tasks to install agent
      ansible.builtin.include_tasks:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/common/templates/tasks/install_s1_agent.yml"
