---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Include s1_agent_install
      include_role:
        name: s1_agent_install

    - name: flush handlers
      meta: flush_handlers

    - name: Show agent version
      ansible.builtin.debug:
        var: s1_agent_version

    - name: Persist facts
      ansible.builtin.set_fact:
        s1_molecule_agent_src: '{{ s1_agent_src }}'
        s1_molecule_agent_version: '{{ s1_agent_version }}'
        cacheable: yes
