---
# tasks file for s1_agent_uninstall

- name: Import OS specific variables
  ansible.builtin.include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - '{{ ansible_system | lower }}.yml'
      skip: yes
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
    label: '{{ loop_vars | basename }}'
  tags:
    - always

- name: Include OS specific tasks
  ansible.builtin.include_tasks:
    file: '{{ loop_family }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - '{{ ansible_system | lower }}.yml'
        - 'unsupported.yml'
  loop_control:
    loop_var: loop_family
    label: '{{ loop_family | basename }}'
  tags:
    - always
