---
# tasks file for s1_agent_uninstall

- name: Get the endpoints passphrase
  ansible.builtin.include_role:
    name: s1_mgmt_get_passphrase
  when:
    - s1_agent_info.installed
    - s1_agent_passphrase is undefined or (ansible_system == 'Linux' and not s1_forced_remove | default('false') | bool)

- name: Include OS specific tasks
  ansible.builtin.include_tasks:
    file: "{{ loop_family }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_system | lower }}.yml"
        - unsupported.yml
  loop_control:
    loop_var: loop_family
    label: "{{ loop_family | basename }}"
  when:
    - s1_agent_info.installed
    - (s1_agent_passphrase is defined) or (s1_forced_remove | default('false') | bool)
