---
# tasks file for s1_agent_uninstall

- name: Get Agent path | Windows
  ansible.windows.win_reg_stat:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\SentinelAgent
    name: ImagePath
  register: s1_image_path

- name: Uninstall SentinelOne agent | Windows
  ansible.windows.win_package:
    creates_service: '{{ s1_service_name }}'
    state: absent
    path: '{{ s1_image_path.value | regex_replace(''"'', '''') | win_dirname }}\uninstall.exe'
    arguments:
      - /uninstall
      - /norestart
      - /quiet
      - /k
      - '{{ s1_agent_passphrase }}'
    wait_for_children: yes
  become: yes
  register: s1_uninstall_log
  when: s1_image_path.exists | bool
  notify: '{{ s1_reboot_handler_name }}'
