---
- name: Prepare
  hosts: all
  gather_facts: yes
  gather_subset:
    - '!all'
    - '!hardware'
    - min
  tasks:
    - name: Include tasks to clean up package managers | Linux
      ansible.builtin.include_tasks:
        file: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../../../s1_agent_common/molecule/common_files/tasks/prepare_package_manager.yml"
      when:
        - ansible_system == 'Linux'

    - name: Clear cached facts
      ansible.builtin.meta: clear_facts
