---
# tasks file for s1_import_rpm_key
- name: Only run when OS Family is RedHat
  block:
    - name: Create working directory | Linux
      ansible.builtin.file:
        path: '{{ s1_workdir }}'
        state: directory
        mode: '0755'

    - name: Copy SentinelOne RPM key | Linux
      ansible.builtin.copy:
        src: sentinel_one.gpg
        dest: '{{ s1_workdir }}'
        mode: '0755'

    - name: Import SentinelOne RPM key | Linux
      ansible.builtin.rpm_key:
        state: '{{ s1_s1_rpm_key_state | default("present") }}'
        key: '{{ s1_workdir }}/sentinel_one.gpg'
      become: yes
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Suse'
