---
# This is an example playbook to execute Ansible tests.

- name: Prepare
  hosts: all
  gather_facts: yes
  gather_subset:
    - '!all'
    - '!hardware'
    - min

  tasks:
    - name: Include tasks to clean up package managers | Linux
      ansible.builtin.include_tasks:
        file: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../../../s1_agent_common/molecule/common_files/tasks/prepare_package_manager.yml"
      when:
        - ansible_system == 'Linux'

    - name: Install SentinelOne Agent
      ansible.builtin.include_role:
        name: s1_agent_install
      vars:
        s1_reboot_handler_name: Reboot Node | {{ ansible_os_family }} | Unit Testing

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Clear cached facts
      ansible.builtin.meta: clear_facts

    - name: Gather facts
      ansible.builtin.setup:

    - name: Get the agent's state
      ansible.builtin.include_role:
        name: s1_agent_info

    - name: Persist facts for verify step
      ansible.builtin.set_fact:
        s1_molecule_installed_version: '{{ s1_agent_info.version }}'
        cacheable: yes

    - name: Wait for agent to register with Management Console
      ansible.builtin.uri:
        url: '{{ s1_management_console }}/web/api/v2.1/agents?uuid={{ s1_agent_info.uuid }}&isActive=true'
        return_content: false
        headers:
          Authorization: 'ApiToken {{ s1_api_token }}'
      environment:
        http_proxy: '{{ s1_agent_management_proxy | default(None) | default(omit) }}'
        https_proxy: '{{ s1_agent_management_proxy | default(None) | default(omit) }}'
      register: s1_agent_registered
      until:
        - s1_agent_registered is not failed
        - s1_agent_registered.json.pagination.totalItems == 1
      retries: 10
      delay: 10
      become: no
      delegate_to: localhost
