---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  roles:
    - s1_agent_common
    - s1_agent_info
  tasks:
    - name: Show agent info
      ansible.builtin.debug:
        var: s1_agent_info

    - name: Assert SentinelOne Agent is not installed
      ansible.builtin.assert:
        that:
          - s1_agent_info is defined
          - not s1_agent_info.installed | bool
