---
# tasks file for s1_agent_uuid

- name: Set the agent's UUID
  ansible.builtin.set_fact:
    s1_agent_uuid: '{{ s1_agent_info.uuid }}'

- name: Gather network facts
  when:
    - s1_agent_uuid_report is defined
    - s1_agent_uuid_report is not none
    - s1_agent_uuid_report | length > 0
  block:
    - name: Gather network facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - dns
          - all_ipv4_addresses
      tags:
        - s1_gather_facts

    - name: Include tasks to write UUIDs to CSV
      ansible.builtin.include_tasks:
        file: uuid_report.yml
