---
- name: Gather facts
  ansible.builtin.setup:

- name: Create passhprase CSV report
  ansible.builtin.template:
    src: uuid_report.csv.j2
    dest: '{{ s1_agent_uuid_report }}'
    mode: 0644
  delegate_to: localhost
  run_once: yes

- name: Agent UUID report path
  ansible.builtin.debug:
    var: s1_agent_uuid_report
  delegate_to: localhost
  run_once: yes
