---
- name: Create UUID CSV report
  ansible.builtin.template:
    src: uuid_report.csv.j2
    dest: "{{ s1_agent_uuid_report }}"
    mode: "0644"
  vars:
    regexp: ^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$
  delegate_to: localhost
  run_once: true

- name: Agent UUID report path
  ansible.builtin.debug:
    var: s1_agent_uuid_report
  delegate_to: localhost
  run_once: true
