---
# This is an example playbook to execute Ansible tests.

- name: Cleanup
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove S1 work directory
      ansible.builtin.file:
        path: '{{ s1_workdir }}'
        state: absent
      run_once: true
      delegate_to: localhost
      become: no
