---
# defaults file for s1_agent_download

# # Directory to be used as a temporary work directory. This path will be used by both the controller and inventory nodes.
# s1_download_path: /tmp/s1_agent_cache

# URL to the SentinelOne management console
s1_management_console: "{{ undef(hint='You must specify your SentinelOne Management Console') }}"
# API token with permissions to access the Packages tab and download agent packages
s1_api_token: "{{ undef(hint='You must specify your SentinelOne API Token') }}"
# Package Availability, used to query the API for available packages
# s1_package_availability:
#   - Beta
#   - Ea
#   - Ga

# Download a specific version of agent
# Because agent versions vary by platform, this must be assigned at the ansible_os_family or a narrower scope
# This the Build Number on Sentinels > Packages pages.
# s1_agent_version: 21.7.3.6

# Download an agent package this many releases behind the latest
# When both s1_agent_version and s1_release_n_minus are unset, the latest release will be downloaded
# s1_release_n_minus: 1

# Download GPG signed RPM packages. Do not change this unless you know what you are doing.
# The s1_import_gpg_key role can be used to install the SentinelOne GPG key on endpoints.
# s1_install_gpg_signed_rpm: no

# Download msi packages instead of SentinelOneInstaller packages. Do not change this unless you know what you are doing.
# s1_install_msi: no
