---
# defaults file for s1_agent_download

# URL to the SentinelOne management console
# s1_management_console:

# API token with permissions to access the Packages tab and download agent packages
# s1_api_token:

# Download a specific version of agent
# Because agent versions vary by platform, this must be assigned at the ansible_os_family or a narrower scope
# This the Build Number on Sentinels > Packages pages.
# s1_agent_version: 21.7.3.6

# Download an agent package this many releases behind the latest
# When both s1_agent_version and s1_release_n_minus are unset, the latest release will be downloaded
# s1_release_n_minus: 1

# Download unsigned RPM packages. Do not change this unless you know what you are doing.
# The s1_import_rpm_key role can be used to install the SentinelOne GPG key on endpoints.
# s1_install_unsigned_rpm: yes
