---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  roles:
    - s1_agent_common
    - s1_agent_info
  tasks:
    - name: Show agent info
      ansible.builtin.debug:
        var: s1_agent_info

    - name: Assert SentinelOne Agent is installed
      ansible.builtin.assert:
        that:
          - s1_agent_info is defined
          - s1_agent_info.installed | bool
          - s1_agent_info.version == s1_molecule_agent_version

    - name: Assert SentinelOne service is running
      ansible.builtin.assert:
        that:
          - s1_agent_info is defined
          - s1_agent_info.service_status == ('running' if ansible_os_family != 'Windows' else 'started')
          - s1_agent_info.agent_enabled == (true | bool)
