---
- name: Gather package facts | Linux
  ansible.builtin.package_facts:
    manager: auto

- name: Gather service facts | Linux
  ansible.builtin.service_facts:

- name: Get agent status | Linux
  ansible.builtin.command: >
    /opt/sentinelone/bin/sentinelctl management status
  register: s1_mgmt_status
  changed_when: no
  check_mode: no
  become: yes
  until: "'Error: receive failed: Connection reset by peer' not in s1_mgmt_status.stdout"
  retries: 3
  delay: 10
  when: ansible_facts.packages[s1_package_name] is defined

- name: Set package facts | Linux
  ansible.builtin.set_fact:
    s1_agent_info:
      installed: '{{ ansible_facts.packages[s1_package_name] is defined | bool }}'
      version: "{{ ansible_facts.packages[s1_package_name] | map(attribute='version') | list | first | default(None) if ansible_facts.packages[s1_package_name] is defined else none }}"
      service_status: "{{ ansible_facts.services[s1_service_name]['state'] if ansible_facts.services[s1_service_name] is defined else none }}"
      product_id: "{{ '' | default(None) }}"
      uuid: "{{ s1_mgmt_status.stdout | regex_search(reg_uuid, '\\1') | first | default(None) if s1_mgmt_status.stdout is defined else none }}"
      reboot_required: '{{ ansible_facts.packages[s1_package_name] is defined | ternary(false, none) }}'
      mgmt_url: "{{ s1_mgmt_status.stdout | regex_search(reg_url, '\\1') | first | default(None) if s1_mgmt_status.stdout is defined else none }}"
      anti_tamper_enabled: "{{ (s1_mgmt_status.stdout | regex_search(reg_tamper, '\\1') | first == 'On') | bool if s1_mgmt_status.stdout is defined else none }}"
      agent_enabled: "{{ (ansible_facts.services[s1_service_name]['status'] == 'enabled') | ternary(true, false) if ansible_facts.services[s1_service_name] is defined else none }}"
  vars:
    reg_uuid: 'UUID\s+([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})'
    reg_url: 'URL\s+(http.*)'
    reg_tamper: 'Anti Tamper\s+(\w+)'
