---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get SentinelOne RPM key | Linux
      ansible.builtin.rpm_key:
        state: present
        key: '{{ s1_workdir }}/sentinel_one.gpg'
      become: yes
      register: s1_molecule_rpm_key
      when: ansible_os_family == 'RedHat'

    - name: Assert that SentinelOne RPM key is installed | Linux
      assert:
        that: not s1_molecule_rpm_key is changed
      when: ansible_os_family == 'RedHat'
