---
# This is an example playbook to execute Ansible tests.

- name: Cleanup
  hosts: all
  gather_facts: false
  tasks:
    - block:
        - name: Import variables
          include_vars: '../../vars/main.yml'

        - name: Remove S1 work directory
          ansible.builtin.file:
            path: '{{ s1_workdir }}'
            state: absent
          run_once: true

      delegate_to: localhost
      become: no
