---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Assert that s1_agent_passphrase is defined
      ansible.builtin.assert:
        that:
          - s1_molecule_agent_passphrase is defined
          - s1_molecule_agent_passphrase is not none
          - s1_molecule_agent_passphrase | length > 0

    - name: Get passphrase report # noqa: run-once[task]
      ansible.builtin.stat:
        path: '{{ s1_agent_passphrase_report }}'
      register: passphrase_report
      delegate_to: localhost
      run_once: yes

    - name: Assert that passphrase report was created # noqa: run-once[task]
      ansible.builtin.assert:
        that: passphrase_report.stat.exists
      delegate_to: localhost
      run_once: yes
