---
# tasks file for s1_agent_common

- name: Gather required facts
  ansible.builtin.setup:
    gather_subset: '{{ default_gather_subset + (role_gather_subset | default([])) }}'
  tags:
    - s1_gather_facts

- name: Show distribution facts
  tags:
    - never
    - debug
  block:
    - name: Show Gathered Facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show supported Linux distributions
      ansible.builtin.debug:
        var: s1_supported_linux_distribution|list

    - name: Show additional supported OS Families
      ansible.builtin.debug:
        var: s1_supported_os_family

    - name: Endpoint details
      ansible.builtin.debug:
        msg:
          - 'Ansible Distribution: {{ ansible_distribution }}'
          - 'Ansible Distribution Version: {{ ansible_distribution_version }}'
          - 'Ansible Distribution Major Version: {{ ansible_distribution_major_version }}'
          - 'Ansible OS Family: {{ ansible_os_family }}'
          - 'Ansible System: {{ ansible_system }}'

    - name: Variables will be loaded from the first matching file in vars
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution | lower | replace(' ', '_') }}_{{ ansible_distribution_version }}.yml"
          - "{{ ansible_distribution | replace(' ', '_') | lower }}_{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_distribution | replace(' ', '_') | lower }}.yml"
          - "{{ ansible_os_family | replace(' ', '_') | lower }}_{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_os_family | replace(' ', '_') | lower }}.yml"
          - "{{ ansible_system | replace(' ', '_') | lower }}.yml"

- name: Set distribution variables
  ansible.builtin.include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower | replace(' ', '_') }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | replace(' ', '_') | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | replace(' ', '_') | lower }}.yml"
        - "{{ ansible_os_family | replace(' ', '_') | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | replace(' ', '_') | lower }}.yml"
        - "{{ ansible_system | replace(' ', '_') | lower }}.yml"
      skip: yes
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
    label: '{{ loop_vars | basename }}'
  tags:
    - always
