---
# tasks file for s1_agent_install

- name: Assert that the operating system is supported
  ansible.builtin.assert:
    that:
      - '(ansible_os_family in s1_supported_os_family) or (ansible_distribution in s1_supported_linux_distribution)'
    # yamllint disable-line rule:line-length
    fail_msg: 'The {{ ansible_distribution }} operating system is not supported by the SentinelOne Agent. Please review the System Requirements Knowledge Base to confirm compatibility.'

- name: Import OS specific variables
  ansible.builtin.include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - '{{ ansible_system | lower }}.yml'
      skip: yes
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
    label: '{{ loop_vars | basename }}'

- name: Assert that s1_agent_site_token is valid
  ansible.builtin.assert:
    that:
      - s1_agent_site_token is defined
      - s1_agent_site_token is not none
      - s1_agent_site_token | length > 0
      - (s1_agent_site_token | b64decode | from_json).site_key is defined
      - (s1_agent_site_token | b64decode | from_json).url is defined
    fail_msg: s1_agent_site_token is not valid
    success_msg: s1_agent_site_token is valid

- name: Download Agent from Management Console
  ansible.builtin.include_role:
    name: s1_agent_download
  when: s1_agent_src is undefined

- name: Include OS specific tasks
  ansible.builtin.include_tasks:
    file: '{{ loop_family }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - '{{ ansible_system | lower }}.yml'
        - 'unsupported.yml'
  loop_control:
    loop_var: loop_family
    label: '{{ loop_family | basename }}'

- name: SentinelOne agent version installed
  ansible.builtin.debug:
    var: s1_agent_version
