---
# tasks file for s1_agent_download
- name: Set task name
  ansible.builtin.set_fact:
    task_name: "{{ (s1_release_n_minus | default(0) == 0) | ternary('Latest ', 'N-' + (s1_release_n_minus | default(0) | string) + ' release') }}"

- name: Set signed RPM SentinelOne agent source | {{ task_name }}
  ansible.builtin.set_fact:
    s1_download_src: "{{ (s1_available_packages.json.data | selectattr('fileExtension', 'equalto', '.rpm') | selectattr('fileName', 'match', '^Signed') | list)[s1_release_n_minus | default(0)] }}"
  when:
    - ansible_os_family is in rpm_distribution
    - not s1_install_unsigned_rpm | default('no') | bool

- name: Set unsigned RPM SentinelOne agent source | {{ task_name }}
  ansible.builtin.set_fact:
    s1_download_src: "{{ (s1_available_packages.json.data | selectattr('fileExtension', 'equalto', '.rpm') | selectattr('fileName', 'match', '^Sentinel') | list)[s1_release_n_minus | default(0)] }}"
  when:
    - ansible_os_family is in rpm_distribution
    - s1_install_unsigned_rpm | default('no') | bool

- name: Set DEB SentinelOne agent source | {{ task_name }}
  ansible.builtin.set_fact:
    s1_download_src: "{{ (s1_available_packages.json.data | selectattr('fileExtension', 'equalto', '.deb') | list)[s1_release_n_minus | default(0)] }}"
  when: ansible_os_family is in apt_distribution

- name: Set MSI SentinelOne agent source | {{ task_name }}
  ansible.builtin.set_fact:
    s1_download_src: "{{ (s1_available_packages.json.data | selectattr('fileExtension', 'equalto', '.msi') | selectattr('osArch', 'equalto', (ansible_facts.architecture == '64-bit') | ternary('64 bit', '32 bit')) | list)[s1_release_n_minus | default(0)] }}"
  when: ansible_os_family == 'Windows'
