---
# verify tasks file for s1_agent_uninstall
- name: Gather package facts | Linux
  ansible.builtin.package_facts:
    manager: auto

- name: Gather service facts | Linux
  ansible.builtin.service_facts:

- name: Check SentinelOne directory | Linux
  ansible.builtin.stat:
    path: '{{ item }}'
  register: s1_install_directory
  with_items:
    - '{{ s1_agent_custom_install_path | default("/opt/sentinelone/") }}'
    - /opt/sentinelone/

- name: Assert SentinelOne service is not installed | Linux
  ansible.builtin.assert:
    that:
      - ansible_facts.services[s1_service_name] is undefined

- name: Assert SentinelOne Agent is not installed | Linux
  ansible.builtin.assert:
    that:
      - ansible_facts.packages[s1_package_name] is undefined

- name: Assert SentinelOne directory is absent | Linux
  ansible.builtin.assert:
    that:
      - s1_install_directory.results | map(attribute='stat') | list | unique | length == 1
      - not ((s1_install_directory.results | map(attribute='stat') | list | first).exists | bool)
