---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Clear cached facts
      ansible.builtin.meta: clear_facts

    - name: Include s1_agent_uuid
      ansible.builtin.include_role:
        name: s1_agent_uuid

    - name: Show agent uuid
      ansible.builtin.debug:
        var: s1_agent_uuid

    - name: Persist facts
      ansible.builtin.set_fact:
        s1_molecule_agent_uuid: "{{ s1_agent_uuid }}"
        cacheable: yes
