name: Continuous Integration
on:
  workflow_call:
    inputs:
      box_distribution:
        description: 'Vagrant Box Operating System'
        type: string
        required: true
      box_repository:
        description: 'Vagrant Box repository'
        type: string
        required: true
      ansible_connection:
        description: 'Ansible connection type for connecting to the Box'
        type: string
        required: false
        default: ssh
      ansible_group:
        description: "Box's Ansible inventory group"
        type: string
        required: false
        default: Linux
      display_name:
        description: 'OS Name to display in workflow steps'
        type: string
        required: true
      scenario_name:
        description: 'Name of the molecule scenario to execute'
        type: string
        required: false
        default: default
      ansible_version:
        description: 'Ansible Version'
        type: string
        required: true
      python_version:
        description: 'Python Version'
        type: string
        required: true

jobs:
  molecule-test:
    # name: '${{ inputs.display_name }} - ${{ inputs.scenario_name }} (Ⓐ ${{ inputs.ansible_version }})'
    runs-on: [self-hosted, Linux, X64, ansible-collection]
    env:
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      S1_AGENT_SITE_TOKEN: ${{ secrets.S1_AGENT_SITE_TOKEN }}
      S1_API_TOKEN: ${{ secrets.S1_API_TOKEN }}
      S1_MANAGEMENT_CONSOLE: ${{ vars.S1_MANAGEMENT_CONSOLE }}
      S1_MOLECULE_HOSTNAME: falling-lab
      VAGRANT_DEFAULT_PROVIDER: virtualbox
      VAGRANT_HOME: /opt/hostedtoolcache/Vagrant

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-setup
        with:
          python_version: ${{ inputs.python_version }}
          ansible_version: ${{ inputs.ansible_version }}

      - name: Set environment
        run: |
          DISTRIBUTION=${{ inputs.box_distribution }}
          REPOSITORY=${{ inputs.box_repository }}
          GROUP=${{ inputs.ansible_group }}
          echo "S1_VAGRANT_DISTRO=${DISTRIBUTION}" >> $GITHUB_ENV
          echo "S1_VAGRANT_REPO=${REPOSITORY}" >> $GITHUB_ENV
          if [ -n "$GROUP" ]; then echo "S1_VAGRANT_GROUP=${GROUP}" >> $GITHUB_ENV; fi

      - name: Assert that variables are defined
        if: ${{ (env.S1_VAGRANT_DISTRO == '') || (env.S1_VAGRANT_REPO == '') }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('S1_VAGRANT_DISTRO and S1_VAGRANT_REPO are not set!')

      - name: Execute Molecule Scenarios
        if: success()
        run: >-
          echo ${PWD} &&
          molecule --version &&
          ansible --version &&
          molecule test --scenario-name ${{ inputs.scenario_name }}
        working-directory: ./roles/s1_agent_download
