name: S1 Import GPG Key
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'roles/s1_import_gpg_key/**'
      - '!roles/s1_import_gpg_key/README.md'
      - '!roles/s1_import_gpg_key/makefile'
      - '.github/workflows/s1_import_gpg_key.yml'
      - '.github/workflows/ci-*.yml'
      - '.github/actions/ci-setup/action.yml'
      - 'requirements.yml'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - 'roles/s1_import_gpg_key/**'
      - '!roles/s1_import_gpg_key/README.md'
      - '!roles/s1_import_gpg_key/makefile'
      - '.github/workflows/s1_import_gpg_key.yml'
      - '.github/workflows/ci-*.yml'
      - '.github/actions/ci-setup/actions.yml'
      - 'requirements.yml'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  call-ci-lint:
    name: Lint Role
    uses: ./.github/workflows/ci-lint.yml
    with:
      role-path: ./roles/s1_import_gpg_key

  call-ci-test:
    name: 'Test: ${{ matrix.boxes.display_name }} (${{ matrix.scenario-name }})'
    needs: call-ci-lint
    uses: ./.github/workflows/ci-test.yml
    strategy:
      fail-fast: false
      matrix:
        boxes:
          # GPG Key only needs to be installed on RPM-based systems
          - distribution: opensuse15
            repository: roboxes
            display_name: OpenSuse 15
          - distribution: rocky8
            repository: roboxes
            display_name: Rocky 8
        scenario-name:
          - default
    with:
      box-distribution: ${{ matrix.boxes.distribution }}
      box-repository: ${{ matrix.boxes.repository }}
      ansible-connection: ${{ matrix.boxes.connection }}
      ansible-group: ${{ matrix.boxes.group }}
      display-name: ${{ matrix.boxes.display_name }}
      scenario-name: ${{ matrix.scenario-name }}
      role-path: ./roles/s1_import_gpg_key
    secrets: inherit

  call-ci-assert:
    name: Assert Success
    needs: call-ci-test
    uses: ./.github/workflows/ci-assert.yml
