name: S1 MGMT Get Passphrase
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'roles/s1_mgmt_get_passphrase/**'
      - 'roles/s1_agent_uuid/**'
      - '!roles/s1_mgmt_get_passphrase/README.md'
      - '!roles/s1_agent_uuid/README.md'
      - '!roles/s1_mgmt_get_passphrase/makefile'
      - '!roles/s1_agent_uuid/makefile'
      - '.github/workflows/s1_mgmt_get_passphrase.yml'
      - '.github/workflows/s1_agent_uuid.yml'
      - '.github/workflows/ci-*.yml'
      - '.github/actions/ci-setup/action.yml'
      - 'requirements.yml'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - 'roles/s1_mgmt_get_passphrase/**'
      - 'roles/s1_agent_uuid/**'
      - '!roles/s1_mgmt_get_passphrase/README.md'
      - '!roles/s1_agent_uuid/README.md'
      - '!roles/s1_mgmt_get_passphrase/makefile'
      - '!roles/s1_agent_uuid/makefile'
      - '.github/workflows/s1_mgmt_get_passphrase.yml'
      - '.github/workflows/s1_agent_uuid.yml'
      - '.github/workflows/ci-*.yml'
      - '.github/actions/ci-setup/actions.yml'
      - 'requirements.yml'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  call-ci-lint:
    name: Lint Role
    uses: ./.github/workflows/ci-lint.yml
    with:
      role-path: ./roles/s1_mgmt_get_passphrase

  call-ci-test:
    name: 'Test: ${{ matrix.boxes.display_name }} (${{ matrix.scenario-name }})'
    needs: call-ci-lint
    uses: ./.github/workflows/ci-test.yml
    strategy:
      fail-fast: false
      matrix:
        boxes:
          - distribution: rocky8
            repository: roboxes
            display_name: Rocky 8
            connection: ssh
          - distribution: ubuntu2204
            repository: roboxes
            display_name: Ubuntu 22.04
            connection: ssh
          - distribution: windows-server-2022-standard
            repository: gusztavvargadr
            display_name: Server 2022
            connection: ssh
            group: Windows
          - distribution: WindowsServer2012R2
            repository: jborean93
            display_name: Server 2012r2
            connection: winrm
        scenario-name:
          - default
          - winrm_default
        exclude:
          # OpenSSH is not supported on Windows Server 2012r2. We need to use
          # custom scenarios configured for winrm connections. Exclude normal
          # scenarios for winrm connections and winrm_* scenarios for ssh
          # connections.
          - { boxes: { connection: winrm }, scenario-name: default }
          - { boxes: { connection: ssh }, scenario-name: winrm_default }
    with:
      box-distribution: ${{ matrix.boxes.distribution }}
      box-repository: ${{ matrix.boxes.repository }}
      ansible-connection: ${{ matrix.boxes.connection }}
      ansible-group: ${{ matrix.boxes.group }}
      display-name: ${{ matrix.boxes.display_name }}
      scenario-name: ${{ matrix.scenario-name }}
      role-path: ./roles/s1_mgmt_get_passphrase
    secrets: inherit

  call-ci-assert:
    name: Assert Success
    needs: call-ci-test
    uses: ./.github/workflows/ci-assert.yml
